import 'package:flutter/material.dart';
import 'package:get/get.dart';

class MyLocale extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "ar": {
          'English':'الانجليزية',
          'Language':'اللغة',
          "Search ....":"البحث ....",
          "En":"AR",
          "Profile":"الملف الشخصي",
          "Home":"الرئيسية",
          "Categories":"الاصناف",
          "Category":"الصنف",
          "Add":"أضف",
          "Favorite":"المفضلة",
          "Profile":"الملف الشخصي",
          "Addresses":"العناوين",
          "FQAs":"سؤال وجواب",
          "About us":"عننا",
          "Contact us":"اتصل بنا ",
          "Support":"الدعم ",
          "Updates":"التحديثات",
          "Log out":"الخروج",
          "all": "الكل",
          "car": "سيارات",
          "mobile": "موبايل ",
          "cloth": "أزياء الملابس",
          "furnit": "ديكور الأثاث",
          "job": "خدمات العمل",
          "electro": "إلكترونيات",
          "computer": "كمبيوتر انترنت",
          "trade": "الأعمال التجارية",
          "Product":"المنتجات",
          "Description ":"وصف للمنتج",
          'User name':'اسم المستخدم'
        },
        "en": {
          "Profile":"Profile",
          'English':'English',
          'Language':'Language',
          "Search ....":"Search .....",
          "En":"En",
          "Home":"Home",
          "Categories":"Categories",
          "Category":"Category",
          "Add":"Add",
          "Favorite":"Favorite",
          "Profile":"Profile",
          "Addresses":"Addresses",
          "FQAs":"FQAs",
          "About us":"About us",
          "Contact us":"Contact us",
          "Support":"Support",
          "Updates":"Update",
          "Log out":"Log out",
          "all": "All",
          "car": "Cars Vechicles",
          "mobile": "Mobiles Numbers ",
          "cloth": "Clothing Fashionest",
          "furnit": "Furniture Decor",
          "job": "Job Services",
          "electro": "Electronics",
          "computer": "Computers Internet",
          "trade": "Trade Businesses",
          "Product":"Product",
          "Description ":"Description for Product",
          'User name':'User name'
        },
      };
}
